version: '3'
services:
  wiki:
    image: nginx:alpine
    restart: always
    volumes:
      - ./wiki:/usr/share/nginx/html:ro
    environment:
      VIRTUAL_HOST: wiki.peneclone.info
      VIRTUAL_PORT: 80
    networks:
      - frontend

  google:
    image: nginx:alpine
    restart: always
    volumes:
      - ./google:/usr/share/nginx/html:ro
    environment:
      VIRTUAL_HOST: google.peneclone.info
      VIRTUAL_PORT: 80
    networks:
      - frontend

  practica:
    image: nginx:alpine
    restart: always
    volumes:
      - ./practica:/usr/share/nginx/html:ro
    environment:
      VIRTUAL_HOST: practica.peneclone.info
      VIRTUAL_PORT: 80
    networks:
      - frontend

networks:
  frontend:
    external:
      name: proxy